# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PayBuddy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PayBuddy

pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'GoogleSignIn'


  target 'PayBuddyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PayBuddyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
